[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/get-started"
  to = "https://player.vimeo.com/video/517495066?allow=%22autoplay;fullscreen%22"
  status = 301
  
[[redirects]]
  from = "/quick-start"
  to = "https://player.vimeo.com/video/517495066?allow=%22autoplay;fullscreen%22"
  status = 301